export const csvData = `Course Code,Class Title,Author,Title,ISBN,Required or Supplemental,Notes,Type of Class,Digital,First Year
SPAN-UA.9050,Advanced spanish,Corpas Jaime,Aula Internacional Plus 5,9788419236104,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
SPAN-UA 9051,Advanced Spanish for Spanish Speakers,López López Silvia,Aula C1. Curso de Español.,9788419236111,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
SPAN-UA 9112,España en Vivo: Spanish Media Writing Workshop,,,,,,Language,,
SPAN-UA 9010,Intensive Elementary Spanish,Corpas Jaime,Aula Internacional Plus 1 (A1),9788419236043,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not avialable,
SPAN-UA 9010,Intensive Elementary Spanish,Corpas Jaime,Aula Internacional Plus 2 (A2),9788419236067,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not avialable,
SPAN-UA 9020,Intensive Intermediate Spanish,Corpas Jaime,Aula Internacional Plus 3 B1,9788418032226,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
SPAN-UA 9015.001,Intensive Spanish for Advanced Beginners,Corpas Jaime,Aula 2 Internacional Plus,9788419236067,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
SPAN-UA 9015.001,Intensive Spanish for Advanced Beginners,Corpas Jaime,Aula 3 Internacional Plus,9788418032226,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
SPAN-UA 9003,INTERMEDIATE SPANISH I,Corpas Jaime,Aula Internacional Plus 3,9788418032226,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
SPAN-UA 9004,Intermediate II,Corpas Jaime,Aula Internacional Plus 4,9788418224461,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
SPAN-UA 9012,Spain in Conversation,"Sans Baulenas N., Martín Peris E., Garmendia Agustín., & Conejo E.",Bitácora 1: curso de español. Libro del alumno Nueva edición.,9788416347643,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
SPAN-UA 9012,Spain in Conversation,"Sans Baulenas N., Martín Peris E., Garmendia Agustín., & Conejo E.",Cuadernillo de clase (Cuaderno de ejercicios + Material extra de clase),,Required,This is a course packet available at Barquillo Print.,Language,Not available,
SPAN-UA.9025,Spain Today,,,,,,Language,,
SPAN-UA 9001,Spanish for Beginners I,Corpas Jaime,Aula Internacional Plus 1 (A1),9788419236043,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
SPAN-UA 9002,Spanish for Beginners II,Corpas Jaime,Aula 2 Internacional Plus,9788419236067,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not avialable,
SPAN-UA 9063,Spanish for Commerce,Prada Marisa de,Entorno empresarial. Español legua extranjera : nivel B1 B2,9788490817339,Required,"Buy it from ""Booksellers"" Bookstore",Language,Not available,
ARTS-UG 9300.M0 / SCA-UA 9721.M01 / LATC-UA 9291.M01,Art and Activism in Madrid's Spanishspeaking Diaspora Communities,,,,,,Content,,
SPAN-UA 9463M01 / IDSEM-UG 9300,Art Before/Beyond/Without Museums,TBA,,,,,Content,,
ARTH-UA 9417,Art and Social Movements in Spain: 1888-1939,,,,,,Content,,
ACC-UF 9102 M01,Arts and Cultures Towards the Crossroads,TBA,,,,,LS First Year Abroad,,
ACC-UF 9102 M02,Arts and Cultures Towards the Crossroads,TBA,,,,,LS First Year Abroad,,
SPAN-UA 9563,Cervantes & Don Quixote,de Cervantes Saavedra Miguel,Don Quixote,9780099469698,Required,"Translated by Edith Grossman and introduction by Harold Bloom a printed edition of the book will be required for the class.You can get the paperback edition, edited by Vintage Classics, at Secret Kingdoms, C/ de Moratín, 7",Content,https://tinyurl.com/4duv5uf8,No
SPAN-UA 9462,CERVANTES: DON QUIJOTE,Cervantes,Don Quijote de la Mancha 1,0-936388-85-4,Required,"edited by Tom Lathrop, Juan de la Cuesta",Content,Not available,
SPAN-UA 9462,CERVANTES: DON QUIJOTE,Cervantes,Quijote de la Mancha 2,0-936388-86-2,Required,"edited by Tom Lathrop, Juan de la Cuesta",Content,Not available,
SOCS-SHU 9237,China Meets Europe,Christiansen T.,The European Union and China (2018),978-1137308290,Required,,Content,Not available,
SOC-UA 9709 / LWSOC-UA 9251,Comparative European and U.S. Human Rights,,,,,,Content,,
HIST-UA 9290.M01 / POL-UA 9516,Comparative Fascism: Italy Germany Spain,,,,,,Content,,
SPAN-UA 9562 / ANTH-UA 9252 / HIST-UA 9264,Contemporary Perspectives on the Civil War and the "Recovery of Historical Memory" in Spain,TBA,,,,,Content,,
POL-UA9994,Contemporary Spanish Politics in Comparative Perspective,TBA,,,,,Content,,
SPAN-UA9260,Cultural History of Spain,,,,,,Content,,
SPAN-UA9360,Culture and Crisis in Contemporary Spain,,,,,,Content,,
CORE-UA 9544,Cultures & Contexts: Global Madrid,,,,,,Content,,
ANTH-UA9093M01/ SCA-UA9890M01/ SOC-UA9690M01,Current Social Political and Urban Challenges to European Cities,,,,,The electronic case study "Malaga: In Search of Its Identity as a Smart City" will be available at the NYU Bookstore website. You will receive an email with the purchase information before the beginning of the semester. The link to the case study will be integrated in NYU Brightspace.,Content,,
CORE-UA 9750,Expressive Culture: Film,TBA,,,,,Content,,
FINC-UB 9002.M01,Foundations of Finance,"Zvi Bodie, Alex Kane, and Alan J. Marcus","Essentials of Investments, 12th Edition",9781265450090,Required,"The required book for this course, Essentials of Investments by Bodie, will be delivered to you digitally. Information in Syllabus",Content,,No
FINC-UB 9002.M02,Foundations of Finance,"Stephen A. Ross, Randolph W. Westerfield, and Bradford D. Jordan","Essentials of Corporate Finance, 11th Ed",9781266335877,Required,,Content,,No
GWC-UF 9102 M01,Global Works and Society in a Changing World,,,,,,LS First Year Abroad,,
GWC-UF 9102 M02,Global Works and Society in a Changing World,TBA,,,,,LS First Year Abroad,,
HIST-UA 9070,History in the Headlines,,,,,,Content,,
IDSEM-UG 9309,Iberian Sketchbook,,,,,,Content,,
TECH-UB.9001,Information Technology In Business and Society,,,,,,Content,,
MKTG-UB 9001 M01,Intro to Marketing,Kerin,"Marketing, 16th ed.",,Required,"The required book for this course, Marketing by Kerin, will be delivered to you digitally. See syllabus for information.",Content,,
SPAN-UA 9466.M01 / MEIS-UA 9707,Islam and Spain,,,,,,Content,,
MUSIC-UH 2420G,Listening to Madrid,TBA,,,,,Content,,
LAGC-UF 9101,LITERATURE AND THE POLITICAL IMAGINATION IN LATIN AMERICA,de las Casas B.,Short Account of the Destruction of the Indies (Penguin Ed.),9780140445626,Required,,Content,Not available,
LAGC-UF 9101,LITERATURE AND THE POLITICAL IMAGINATION IN LATIN AMERICA,Freire Paulo,Pedagogy of the Oppressed (Penguin Ed.),978-0241301111,Required,,Content,,
LAGC-UF 9101,LITERATURE AND THE POLITICAL IMAGINATION IN LATIN AMERICA,Tobar H.,Our Migrant Souls (Picador Ed.),978-1250335814,Required,,Content,Not available,
ELEC-UF 9101,Madrid in Action: Culture and Community,TBA,,,,,LS First Year Abroad,,
IDSEM-UG9308,Madrid: Faces of the Changing European City,,,,,,Content,,
SOC-UA 9970 / SPAN-UA 9360,MADRID: URBAN VISIONS,Augé Marc,Los no lugares. Espacios del anonimato.,,,p.97-118,Content,https://tinyurl.com/bddbmdfr,
SOC-UA 9970 / SPAN-UA 9360,MADRID: URBAN VISIONS,Harvey David,Ciudades Rebeldes. Del derecho de la ciudad a la revolución urbana,,,p.24-36,Content,https://tinyurl.com/4fk2hds9,
SOC-UA 9970 / SPAN-UA 9360,MADRID: URBAN VISIONS,Lipovetsky G.,La Felicidad Paradójica,9788433973863,,p.197-226,Content,Not available,
SPAN-UA 9471.M01 / JOUR-UA 9204,Madrid Stories: Engaging with Madrid,,,,,,Content,,
MGMT-UB.9001,Management and Organizations,,,,,,Content,,
ARTH-UA.9338,MASTERPIECES IN THE PRADO MUSEUM,Tomlinson Janis,From El Greco to Goya. Painting in Spain 1561-1828,0-8109-2740-3,Required,Copies available in library,Content,Not available,
ARTH-UA.9338,MASTERPIECES IN THE PRADO MUSEUM,Brown Jonathan,Painting in Spain 1500-1700,0-300-06474-8,Required,Copies available in library,Content,Not available,
ARTH-UA 9328,Masterpieces in the Prado Museum,,,,,,Content,,
SPAN-UA 9475 / ANTH-UA 9256 M01,Migration and Cultural Diversity in Spain: Anthropological Approaches,Haas Hein de,The age of migration : international population movements in the modern world,9781462542895,Required,"Syllabus calls for 5th ed., which has been replaced by the 6th ed., ISBN 978-1-4625-4289-5",Content,Not available,
SOIM-UB.9065,Organizational Comm & Its Social Context,,,,,,Content,,
PERF-UT 9103,Performance of the City: Madrid,,,,,,Content,,
POL-UA 9726,Political Economy of Developing Countries,,,,,,Content,,
POL-UA 9167.M01,Spain and the EU,,,,,,Content,,
SPAN-UA 9361 / DRLIT-UA 9551,Spanish Culture Through Cinema,TBA,,,,,Content,,
CORE-UA 9400,Texts and Ideas: Visible and Invisible Cities,,,,,,Content,,
SPAN-UA 9155,Topics in Culture and Action: Fútbol in Spain,TBA,,,,,Content,,
SPAN-UA 9108,Translation Through Contemporary Film,,,,,,Content,,
SPAN-UA9062,Understanding Current Issues in Spain,,,,,,Language,,
WRCI-UF 9102 Colmena,Writing as Exploration,Edwards Steve,Photography : A Very Short Introduction,9780192801647,Required,Students will receive a booklet with the written materials necessary for the course.,LS First Year Abroad,https://ebookcentral-proquest-com.proxy.library.nyu.edu/lib/nyulibrary-ebooks/detail.action?docID=430807,
WRCI-UF 9102 Wuebben,Writing as Exploration,,,,,,,LS First Year Abroad,`;